In [1]:
import numpy as np

In [7]:
B = np.zeros((4, 4))

In [8]:
B[0, 1] = 1
B[1, 2] = 1
B[2, 3] = 1

In [9]:
B

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [10]:
print(B@B)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
