In [37]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split


In [ ]:
B = np.array([ 
    [1.0, 0.8, 0.2, 0.0],
    [0.8, 1.0, 0.3, 0.1],
    [0.2, 0.3, 1.0, 0.6],
    [0.0, 0.1, 0.6, 1.0]
])

In [43]:
T = B.shape[0]     # Longueur des séquences
D = 50         # Dimension des vecteurs X^t
N = 10000          # Nombre d'échantillons

In [5]:
def factorise(B, tol=1e-8):
    # Vérification symétrie
    if not np.allclose(B, B.T, atol=tol):
        raise ValueError("La matrice B n'est pas symétrique.")

    # Décomposition spectrale
    eigvals, eigvecs = np.linalg.eigh(B)

    # Vérification semi-définie positive
    if np.any(eigvals < -tol):
        raise ValueError("La matrice B n'est pas semi-définie positive.")

    # Construction de C = U Λ^{1/2}
    sqrt_eigvals = np.sqrt(np.clip(eigvals, 0, None))
    C = eigvecs @ np.diag(sqrt_eigvals)

    return C

In [15]:

def generate_X(C, N, D):
    T = C.shape[0]
    Z = np.random.randn(N, D, T)  # Z ~ N(0, I)
    X = np.einsum('ndt,ts->nds', Z, C.T)  # équivalent à batch matmul Z @ C.T
    return X

In [ ]:
C = factorise(B)
X_samples = generate_X(C, N=1000, D=10)

# Estimation de E[X^T X]
B_est = np.mean([X.T @ X for X in X_samples], axis=0) / 10
print(B_est)

[[ 0.98324317  0.77676622  0.19439341 -0.01276158]
 [ 0.77676622  0.97135208  0.28575321  0.09112401]
 [ 0.19439341  0.28575321  0.98336761  0.58428362]
 [-0.01276158  0.09112401  0.58428362  0.99345742]]


In [23]:
def compute_moments(B, T_max):
    """
    Calcule (B, B^2, ..., B^T_max) et les empile dans un tenseur (T_max, T, T)
    """
    moments = [B]
    for _ in range(1, T_max):
        moments.append(moments[-1] @ B)
    return np.stack(moments, axis=0)

In [24]:
print(compute_moments(B, T_max=4))

[[[1.     0.8    0.2    0.    ]
  [0.8    1.     0.3    0.1   ]
  [0.2    0.3    1.     0.6   ]
  [0.     0.1    0.6    1.    ]]

 [[1.68   1.66   0.64   0.2   ]
  [1.66   1.74   0.82   0.38  ]
  [0.64   0.82   1.49   1.23  ]
  [0.2    0.38   1.23   1.37  ]]

 [[3.136  3.216  1.594  0.75  ]
  [3.216  3.352  1.902  1.046 ]
  [1.594  1.902  2.602  2.206 ]
  [0.75   1.046  2.206  2.146 ]]

 [[6.0276 6.278  3.636  2.028 ]
  [6.278  6.6    4.1784 2.5224]
  [3.636  4.1784 4.815  3.9574]
  [2.028  2.5224 3.9574 3.5742]]]


In [19]:

def generate_dataset(N, D, T, seed=None):
    if seed is not None:
        np.random.seed(seed)
    
    # Choix aléatoire d'une matrice B (SDP)
    A = np.random.randn(T, T)
    B_true = A @ A.T  # symétrique SDP
    B_true /= np.trace(B_true)  # normalisation optionnelle

    # Factorisation pour générer X
    C = factorise(B_true)
    X_samples = generate_X(C, N, D)

    # Création de (X, y)
    X_data = X_samples
    y_data = np.array([compute_moments(X.T @ X / D, T) for X in X_samples])  # normalisé

    return X_data, y_data

In [25]:

X, y = generate_dataset(N, D, T)

print("X.shape :", X.shape)  # (N, D, T)
print("y.shape :", y.shape)  # (N, T * T * T)


X.shape : (1000, 50, 4)
y.shape : (1000, 4, 4, 4)


In [29]:
class MomentDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [39]:
X, y = generate_dataset(N, D, T, seed=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

train_dataset = MomentDataset(X_train, y_train)
test_dataset  = MomentDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_dataset, batch_size=32, shuffle=False)


In [27]:
class MomentTransformer(nn.Module):
    def __init__(self, d_model, nhead, num_layers, dim_feedforward, T):
        super().__init__()
        self.T = T

        # Embedding linéaire initial (projeté à d_model)
        self.input_proj = nn.Linear(d_model, d_model)

        # Encodage de position appris
        self.pos_embedding = nn.Parameter(torch.randn(1, T, d_model))

        # Transformer encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=dim_feedforward, batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Projection vers une matrice T x T pour chaque moment (T moments au total)
        self.output_proj = nn.Linear(d_model, T * T * T)

    def forward(self, x):
        # x: (batch_size, D, T)
        x = x.permute(0, 2, 1)  # -> (batch_size, T, D)
        x = self.input_proj(x)  # -> (batch_size, T, d_model)

        # Ajout du positional embedding
        x = x + self.pos_embedding  # broadcasting sur batch

        # Passage dans le Transformer
        x = self.transformer(x)  # (batch_size, T, d_model)

        # Moyenne globale ou moyenne sur les positions
        x_pooled = x.mean(dim=1)  # (batch_size, d_model)

        # Projection finale
        y_hat = self.output_proj(x_pooled)  # (batch_size, T*T*T)
        y_hat = y_hat.view(-1, self.T, self.T, self.T)  # reshape en tenseur de moments

        return y_hat


In [45]:
model = MomentTransformer(
    d_model=D,     # correspond à la dimension des vecteurs d'entrée
    nhead=2,
    num_layers=2,
    dim_feedforward=128,
    T=T
)


In [46]:
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

In [47]:
def evaluate(model, dataloader, device):
    model.eval()
    total_loss = 0
    with torch.no_grad():
        for X_batch, y_batch in dataloader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()

    return total_loss / len(dataloader)


In [48]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

for epoch in range(100):  # nombre d'epochs
    model.train()
    total_loss = 0

    for X_batch, y_batch in train_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad()
        y_pred = model(X_batch)  # prédiction
        loss = criterion(y_pred, y_batch)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    
    # Évaluation sur le jeu de test
    test_loss = evaluate(model, test_loader, device)


    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}, Train Loss: {avg_loss:.4f}, Test Loss: {test_loss:.4f}")


Epoch 1, Train Loss: 0.0267, Test Loss: 0.0052
Epoch 2, Train Loss: 0.0068, Test Loss: 0.0035
Epoch 3, Train Loss: 0.0056, Test Loss: 0.0031
Epoch 4, Train Loss: 0.0050, Test Loss: 0.0030
Epoch 5, Train Loss: 0.0047, Test Loss: 0.0029
Epoch 6, Train Loss: 0.0044, Test Loss: 0.0029
Epoch 7, Train Loss: 0.0042, Test Loss: 0.0028
Epoch 8, Train Loss: 0.0040, Test Loss: 0.0028
Epoch 9, Train Loss: 0.0038, Test Loss: 0.0028
Epoch 10, Train Loss: 0.0037, Test Loss: 0.0029
Epoch 11, Train Loss: 0.0036, Test Loss: 0.0029
Epoch 12, Train Loss: 0.0035, Test Loss: 0.0027
Epoch 13, Train Loss: 0.0034, Test Loss: 0.0027
Epoch 14, Train Loss: 0.0033, Test Loss: 0.0027
Epoch 15, Train Loss: 0.0032, Test Loss: 0.0027
Epoch 16, Train Loss: 0.0031, Test Loss: 0.0028
Epoch 17, Train Loss: 0.0030, Test Loss: 0.0028
Epoch 18, Train Loss: 0.0029, Test Loss: 0.0027
Epoch 19, Train Loss: 0.0028, Test Loss: 0.0026
Epoch 20, Train Loss: 0.0026, Test Loss: 0.0026
Epoch 21, Train Loss: 0.0025, Test Loss: 0.0028
E