In [14]:
import numpy as np
import torch
import torch.nn.functional as F

In [21]:
QK = np.zeros((4,
               4))

In [22]:
QK[0,1] = 1
QK[1,1] = 100
QK[2,1] = 1
QK[3,1] = 100
QK

array([[  0.,   1.,   0.,   0.],
       [  0., 100.,   0.,   0.],
       [  0.,   1.,   0.,   0.],
       [  0., 100.,   0.,   0.]])

In [23]:
# get torch tensor
QK = torch.from_numpy(QK)

In [24]:
QK

tensor([[  0.,   1.,   0.,   0.],
        [  0., 100.,   0.,   0.],
        [  0.,   1.,   0.,   0.],
        [  0., 100.,   0.,   0.]], dtype=torch.float64)

In [25]:
print(F.softmax(QK, dim=-1))

tensor([[1.7488e-01, 4.7537e-01, 1.7488e-01, 1.7488e-01],
        [3.7201e-44, 1.0000e+00, 3.7201e-44, 3.7201e-44],
        [1.7488e-01, 4.7537e-01, 1.7488e-01, 1.7488e-01],
        [3.7201e-44, 1.0000e+00, 3.7201e-44, 3.7201e-44]], dtype=torch.float64)
